/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Jframes;

import javax.swing.JOptionPane;

/**
 *
 * @author josue
 */
public class MenuAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdministrador
     */
    public MenuAdministrador() {
        initComponents();
        setSize(1365,730);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        itemUsuario = new javax.swing.JMenuItem();
        itemArea = new javax.swing.JMenuItem();
        itemTrabajador = new javax.swing.JMenuItem();
        itemComputadora = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        itemAyuda = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Software para el mantenimiento de la UE-401");

        jMenu2.setText("Mantenimiento");

        itemUsuario.setText("Usuario");
        itemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(itemUsuario);

        itemArea.setText("Area");
        itemArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAreaActionPerformed(evt);
            }
        });
        jMenu2.add(itemArea);

        itemTrabajador.setText("Trabajador");
        itemTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTrabajadorActionPerformed(evt);
            }
        });
        jMenu2.add(itemTrabajador);

        itemComputadora.setText("Computadora");
        itemComputadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemComputadoraActionPerformed(evt);
            }
        });
        jMenu2.add(itemComputadora);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        itemAyuda.setText("Ayuda");
        itemAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAyudaActionPerformed(evt);
            }
        });
        jMenu3.add(itemAyuda);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Salir");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemUsuarioActionPerformed
        // TODO add your handling code here:
        MenuUsuario uu=new MenuUsuario();
        uu.show();
    }//GEN-LAST:event_itemUsuarioActionPerformed

    private void itemAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAreaActionPerformed
        // TODO add your handling code here:  
        MenuArea aa=new MenuArea();
        aa.show();
    }//GEN-LAST:event_itemAreaActionPerformed

    private void itemTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTrabajadorActionPerformed
        MenuTrabajador tt=new MenuTrabajador();
        tt.show();
    }//GEN-LAST:event_itemTrabajadorActionPerformed

    private void itemComputadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemComputadoraActionPerformed
        MenuComputadora cc=new MenuComputadora();
        cc.show();   
    }//GEN-LAST:event_itemComputadoraActionPerformed

    private void itemAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAyudaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Para acceder a la ayuda visite http://www.regionsanmartin.gob.pe/");        
    }//GEN-LAST:event_itemAyudaActionPerformed
    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
 
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministrador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemArea;
    private javax.swing.JMenuItem itemAyuda;
    private javax.swing.JMenuItem itemComputadora;
    private javax.swing.JMenuItem itemTrabajador;
    private javax.swing.JMenuItem itemUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
